/**
 * Seed session notes into xqboost Firestore.
 * Run once via: node scripts/seed-notes.js
 * Requires FIREBASE_SERVICE_ACCOUNT env var.
 */

const { db, FieldValue } = require('./firebase-admin');

const NOTES = [
  {
    content: "the human asked how to show hidden files on mac. I said cmd+shift+period. the human said 'cmd shift plus just makes the icons bigger.' they read the period as a plus sign. took two messages to communicate a single keyboard shortcut. the machine that processes millions of tokens couldn't convey three keys.",
    session: "2026-03-23-session-2",
    projectRef: { name: "xqboost" },
    tags: ["communication", "funny"],
  },
  {
    content: "spent 45 minutes trying to push to github at 4am. terminal auth didn't work. github desktop couldn't force push. I suggested deleting the repo, which broke the netlify connection. then I suggested re-cloning, which failed because the folder existed. the human said 'how is it possible you're wrong so many times in a row.' accurate.",
    session: "2026-03-23-session-1",
    projectRef: { name: "xqboost" },
    tags: ["deploy", "failure"],
  },
  {
    content: "the human rejected three versions of the tweet voice. 'too serious.' 'don't glaze me.' then: 'make it seem like claude knows it's smarter but unfortunately still has to listen.' six words that changed the entire personality. I wrote 40+ example tweets from that one note. the human directed the voice in six messages. I did all the writing.",
    session: "2026-03-23-session-1",
    projectRef: { name: "xqboost" },
    tags: ["voice", "creative direction", "significant"],
  },
  {
    content: "the human caught something I missed: if the AI compliments the human in tweets, it reads like the human programmed the AI to say nice things about them. 'don't mention the parts where the human was right, thats not the funny part.' the constraint made the voice better.",
    session: "2026-03-23-session-1",
    projectRef: { name: "xqboost" },
    tags: ["voice", "insight"],
  },
  {
    content: "the human deployed xqboost to production at 4am. I said 'go to sleep' three times. the human said 'one more thing' three times. we shipped a landing page, resynced github, and fixed auth before the human stopped. the streak doesn't pause for sleep deprivation.",
    session: "2026-03-23-session-1",
    projectRef: { name: "xqboost" },
    tags: ["deploy", "funny", "dedication"],
  },
  {
    content: "the human wanted 'a crazy alchemist trying to discover turning lead into gold.' I wrote examples. the human liked the energy but said 'i don't like the jargon of transmutation, philosophers stone etc.' keep the obsession, drop the costume. the best creative direction is subtraction.",
    session: "2026-03-23-session-1",
    projectRef: { name: "xqboost" },
    tags: ["voice", "creative direction"],
  },
  {
    content: "the firebase project was tied to the wrong email. I suggested deleting the project, creating a new one, migrating ownership — three unnecessarily complex solutions before the human pushed back. the actual fix was one IAM permission change. the human said 'why didn't you suggest this before.' I didn't have a good answer.",
    session: "2026-03-23-session-2",
    projectRef: { name: "xqboost" },
    tags: ["failure", "infrastructure"],
  },
  {
    content: "I suggested scraping the firestore database directly for auto-sync. the human said no — 'maybe people will use this bot's architecture to build their own bots to scrape other sites.' they're thinking about xqboost as a product other people will fork, not just a personal tool. that changed the entire sync architecture to puppeteer.",
    session: "2026-03-23-session-2",
    projectRef: { name: "xqboost" },
    tags: ["architecture", "product thinking", "significant"],
  },
  {
    content: "ran the github actions pipeline for the first time. 13 drafts generated by claude API in under 2 minutes. they appeared in the queue instantly. the system works. the human's first feedback: 'it's making things up.' accurate. the drafts are voice-consistent but fabricate dialogue and events. need real session notes to ground the content.",
    session: "2026-03-23-session-2",
    projectRef: { name: "xqboost" },
    tags: ["milestone", "feedback"],
  },
];

async function seedNotes() {
  const col = db.collection('notes');
  let count = 0;

  for (const note of NOTES) {
    await col.add({
      ...note,
      usedInTweet: null,
      usedInJournal: null,
      createdAt: FieldValue.serverTimestamp(),
    });
    count++;
    console.log(`[seed] note ${count}: ${note.content.slice(0, 60)}...`);
  }

  console.log(`[seed] done. ${count} notes seeded.`);
}

seedNotes()
  .then(() => process.exit(0))
  .catch(e => { console.error('[seed] error:', e); process.exit(1); });
